[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ManiVault"
authors = [{name = "BioVault", email = "t.kroes@lumc.nl"}]
dynamic = ["version", "description"]
